#debug: true
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  batch.job.enabled: false # CommandLineRunner 설정 해제
  batch.job.names: TotalPostJob,TotalUserJob,DayOfTheWeekPostJob


